# config/functions.yml
api:
  handler: app.server
  events:
    - http:
        path: /
        method: ANY
        cors: true
    - http:
        path: /{proxy+}
        method: ANY
        cors: true
    # Auth endpoints
    - http:
        path: /auth/login
        method: POST
        cors: true
    - http:
        path: /auth/register
        method: POST
        cors: true
    # Referral endpoints
    - http:
        path: /referral/create
        method: POST
        cors: true
    - http:
        path: /referral/stats
        method: GET
        cors: true
    - http:
        path: /referral/payouts
        method: GET
        cors: true
    # Stripe endpoints
    - http:
        path: /stripe/connect
        method: POST
        cors: true
    - http:
        path: /stripe/webhook
        method: POST
        cors: true
    # User endpoints
    - http:
        path: /user/profile
        method: GET
        cors: true
    - http:
        path: /user/update
        method: PUT
        cors: true